### ISSUE TITLE
Desk Class

### ISSUE THREAD

**Issue by blip2** [BuildSysUniformMetadata/GroundTruth#5]
I'm currently using the Space object as a stand-in for a "Desk" which hosts sensors and information relating to that workspace (where the desk could potentially move floors in a building) - would a desk object be a useful addition to the schema or is that too specific?

**Comment by jbkoh** [comment]
Hi,
I'd say Desk is an Equipment and Equipment's location can vary across time (though we haven't modeled the location changes yet). Sensors can belong to Desk (like power, height, etc.). Before I say it's better be included in the schema or not, I would like to see how much use cases it has. Is it common to model desks in your data model? In the use cases Brick developers had, desk was just furniture, which we didn't have to track its data. It might have been challenged for the new sensor-enabled desks. If possible, could you describe your use case briefly?

**Comment by blip2** [comment]
Hi,
I would agree that desks would be liable to move (by design!) however we are already integrating sensors and control into desks and would like to capture these along with the more typical building sensors and controls: see https://allaboutthedesk.arup.com/
Thoughts?

**Comment by jbkoh** [comment]
The desk looks very interesting and I'd like to see more like this. It could be defined under brick:Equipment possibly as a subclass of new Furniture class. Another Brick developer previously studied similar topic with chairs, who might have interest in this too (@gtfierro thoughts?). I will bring this issue to the discussion in the future. It'd be also great if you could suggest some skeleton class/relationships capturing common features in such desks.

Note that the official repository has been changed to [here](https://github.com/BuildSysUniformMetadata/Brick). Please continue this discussion at [the issue there](https://github.com/BuildSysUniformMetadata/Brick/issues/15).

**Comment by gtfierro** [comment]
Closing this issue to defer discussion to https://github.com/BuildSysUniformMetadata/Brick/issues/15
