### ISSUE TITLE
Duplicated data

### ISSUE THREAD

**Issue by ponnou** [BuildSysUniformMetadata/GroundTruth#7]
Hello,

I would like to report an issue with Brick.ttl, indeed we can see that some data are duplicated as shown below.

![image](https://user-images.githubusercontent.com/13155852/28575622-784e5056-711f-11e7-9a05-6dd3a0ff9159.png)

**Comment by jbkoh** [comment]
It looks like this is caused by CO2_Sensor being a subclass of CO2_Sensor itself. I will fix it tonight. Thanks for the report!

**Comment by jbkoh** [comment]
I am closing this issue after migrating this issue to the currently active repository.
