### ISSUE TITLE
Mentioning the License within the ontology and its documentation

### ISSUE THREAD

**Issue by GeorgFerdinandSchneider** [BuildSysUniformMetadata/GroundTruth#8]
Dear Brick development team!

it might be helpful for people reusing BRICK to have the license mentioned within the ontology meta-data, via the dcterms:license annotation property. For example in [Turtle syntax](https://www.w3.org/TeamSubmission/turtle/):

```turtle
@prefix dcterms: <http://purl.org/dc/terms/> .
<https://brickschema.org/schema/1.0.2/BrickFrame> dcterms:license <https://raw.githubusercontent.com/BuildSysUniformMetadata/GroundTruth/master/LICENSE> .
```
or similarly.

Best

Georg

**Comment by jbkoh** [comment]
Hi Georg, Thanks for the suggestion. I will add it tomorrow and let you know. It will be included in the release version 1.0.3

I migrate this issue to the main repository: https://github.com/BuildSysUniformMetadata/Brick/issues/41

Thank you!
